-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(sales*PRICE) TOTAL_SALES
FROM BOOK_SALES A
JOIN BOOK B ON A.BOOK_ID=B.BOOK_ID
JOIN AUTHOR C ON B.AUTHOR_ID=C.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;