-- 코드를 작성해주세요
WITH RANKING_TABLE AS (SELECT *,  RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) RANKING, COUNT(*) OVER () TOTAL_COUNT
                       FROM ECOLI_DATA)
SELECT ID, CASE
                WHEN RANKING<=TOTAL_COUNT/4 THEN 'CRITICAL'
                WHEN RANKING<=TOTAL_COUNT/4*2 THEN 'HIGH'
                WHEN RANKING<=TOTAL_COUNT/4*3 THEN 'MEDIUM'
                ELSE 'LOW'
                END COLONY_NAME
FROM RANKING_TABLE
ORDER BY ID;