-- 코드를 입력하세요
SET @ALL_USER=(SELECT COUNT(*)
               FROM USER_INFO
               WHERE YEAR(JOINED)=2021);
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/@ALL_USER, 1) PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                  FROM USER_INFO
                  WHERE YEAR(JOINED)=2021)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE);