-- 코드를 입력하세요
SELECT B.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW A
JOIN MEMBER_PROFILE B ON A.MEMBER_ID=B.MEMBER_ID
WHERE A.MEMBER_ID=(SELECT A.MEMBER_ID
                   FROM REST_REVIEW A
                   JOIN MEMBER_PROFILE B ON A.MEMBER_ID=B.MEMBER_ID
                   GROUP BY MEMBER_ID
                   ORDER BY COUNT(*) DESC
                   LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;