-- 코드를 입력하세요
SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID=B.CAR_ID
WHERE DATE_FORMAT(A.START_DATE,'%Y-%m')='2022-10' AND B.CAR_TYPE='세단'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;